name: Update Professor News

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-professor-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
          pip install requests

      - name: Run news update script
        run: python scrape-professor-news.py

      - name: Commit changes if any
        env:
          REPO_URL: "https://github.com/${{ github.repository }}/blob/main"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          changed_files=$(git status --porcelain | awk '{print $2}')

          for file in $changed_files; do
            if [[ -d $file ]]; then
              # If the entry is a directory, check for news.html
              news_file="${file}news.html"
              if [[ ! -f "$news_file" ]]; then
                continue
              fi
              file="$news_file"
            fi
          
            if [[ $file == professors/*/news.html ]]; then
              professor_name=$(echo "$file" | sed -E 's|professors/(.*)/news.html|\1|' | sed 's|/$||' | sed 's/_/ /g')
              commit_message="Update news for $(echo "$professor_name" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')"
              
              git add "$file"
              git commit -m "$commit_message"
          
              # Push after each commit to get the correct commit hash
              git push
              commit_hash=$(git rev-parse HEAD)
          
              # Generate URLs for the updated file and the commit
              file_url="sapienzastudents.net/sapienzafeed/${file}"
              commit_url="https://github.com/${{ github.repository }}/commit/$commit_hash"
          
              # Send Telegram Notification
              python send-professor-news-update-to-telegram.py "$professor_name" "$file_url" "$commit_url" "${{ secrets.TELEGRAM_BOT_TOKEN }}" "${{ secrets.TELEGRAM_CHAT_ID }}"
            fi
          done
